
services:
  api:
    build: ../server
    container_name: fitapp-api
    environment:
      - APP_ENV=docker
      - ALLOWED_ORIGINS=*
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=fitapp
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=us-east-1
      - S3_BUCKET=uploads
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_USE_SSL=false
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - minio

  worker:
    build: ../server
    container_name: fitapp-worker
    environment:
      - APP_ENV=docker
      - ALLOWED_ORIGINS=*
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=fitapp
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=us-east-1
      - S3_BUCKET=uploads
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_USE_SSL=false
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: celery -A celery_app.celery_app worker --loglevel=INFO
    depends_on:
      - redis
      - mongo
      - minio

  mongo:
    image: mongo:7
    container_name: fitapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: fitapp-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: fitapp-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  mongo-data:
  minio-data:
